version: 0.0
os: linux
 
hooks:
  ApplicationStop:
    - location: munib-scripts/stop_container.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: munib-scripts/start_container.sh
      timeout: 300
      runas: root
